<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Produto;
use App\Models\Categoria;

class ProdutoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Busca as categorias pelos nomes
        $paoSaladinha = Categoria::where('nome', 'Pão de Saladinha')->first();
        $paoHamburguer = Categoria::where('nome', 'Pão de Hambúrguer')->first();
        $xpicanhaFile = Categoria::where('nome', 'X-Picanha / Filé')->first();
        $xfrango = Categoria::where('nome', 'X-Frango')->first();
        $xcalabresaBacon = Categoria::where('nome', 'X-Calabresa / Bacon')->first();
        $lanchesPrato = Categoria::where('nome', 'Lanches no Prato')->first();
        $porcoes = Categoria::where('nome', 'Porções')->first();
        $acrescimos = Categoria::where('nome', 'Acréscimos')->first();
        $bebidas = Categoria::where('nome', 'Bebidas')->first();

        $produtos = [
            // --- PÃO DE SALADINHA ---
            [
                'nome' => 'Saladinha',
                'descricao' => 'Alface, tomate, hambúrguer, presunto e queijo',
                'preco' => 19.00,
                'categoria_id' => $paoSaladinha->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Saladinha Frango',
                'descricao' => 'Alface, tomate, hambúrguer, frango, presunto e queijo',
                'preco' => 25.00,
                'categoria_id' => $paoSaladinha->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Saladinha Bacon',
                'descricao' => 'Alface, tomate, hambúrguer, bacon, presunto e queijo',
                'preco' => 25.00,
                'categoria_id' => $paoSaladinha->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Saladinha Calabresa',
                'descricao' => 'Alface, tomate, hambúrguer, calabresa, presunto e queijo',
                'preco' => 25.00,
                'categoria_id' => $paoSaladinha->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Saladinha Duplo',
                'descricao' => 'Alface, tomate, 2 hambúrgueres, presunto e queijo',
                'preco' => 25.00,
                'categoria_id' => $paoSaladinha->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Tetinha',
                'descricao' => 'Alface, tomate, cebola, filé, salsicha, ovo, batata palha, presunto e queijo',
                'preco' => 27.00,
                'categoria_id' => $paoSaladinha->id,
                'disponivel' => true,
                'imagem' => null,
            ],

            // --- PÃO DE HAMBÚRGUER ---
            [
                'nome' => 'Hot Dog',
                'descricao' => 'Alface, tomate, batata palha, 2 salsichas, presunto e queijo',
                'preco' => 21.00,
                'categoria_id' => $paoHamburguer->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Hot Dog Especial',
                'descricao' => 'Alface, tomate, milho, ervilha, batata palha, 2 salsichas, hambúrguer, ovo, presunto e queijo',
                'preco' => 29.00,
                'categoria_id' => $paoHamburguer->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Bauru',
                'descricao' => 'Tomate, presunto e queijo',
                'preco' => 23.00,
                'categoria_id' => $paoHamburguer->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Prensado',
                'descricao' => 'Tomate, milho, ervilha, batata palha, presunto e queijo',
                'preco' => 26.00,
                'categoria_id' => $paoHamburguer->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Salada',
                'descricao' => 'Alface, tomate, hambúrguer, presunto e queijo',
                'preco' => 24.00,
                'categoria_id' => $paoHamburguer->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Misto Quente',
                'descricao' => null,
                'preco' => 23.00,
                'categoria_id' => $paoHamburguer->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Burguer',
                'descricao' => 'Tomate, hambúrguer, 2 presuntos e 2 queijos',
                'preco' => 26.00,
                'categoria_id' => $paoHamburguer->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Burguer Egg',
                'descricao' => 'Tomate, hambúrguer, ovo, presunto e queijo',
                'preco' => 26.00,
                'categoria_id' => $paoHamburguer->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Mais',
                'descricao' => 'Tomate, milho, ervilha, bacon, calabresa, ovo, salsicha, hambúrguer, frango, filé, presunto e queijo',
                'preco' => 40.00,
                'categoria_id' => $paoHamburguer->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Atum',
                'descricao' => 'Alface, tomate, milho, ervilha, cebola, atum, ovo e 2 fatias de queijo',
                'preco' => 29.00,
                'categoria_id' => $paoHamburguer->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Palmito',
                'descricao' => 'Alface, tomate, milho, ervilha, cebola, palmito, azeitona e 2 fatias de queijo',
                'preco' => 29.00,
                'categoria_id' => $paoHamburguer->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Vegetariano',
                'descricao' => 'Alface, tomate, milho, ervilha, cebola, 2 ovos e 3 fatias de queijo',
                'preco' => 27.00,
                'categoria_id' => $paoHamburguer->id,
                'disponivel' => true,
                'imagem' => null,
            ],

            // --- X-PICANHA / FILÉ ---
            [
                'nome' => 'X-Picanha',
                'descricao' => 'Alface, tomate, cebola, picanha e queijo',
                'preco' => 40.00,
                'categoria_id' => $xpicanhaFile->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Picanha Cheddar',
                'descricao' => 'Alface, tomate, cebola, picanha, cheddar e queijo',
                'preco' => 42.00,
                'categoria_id' => $xpicanhaFile->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Filé',
                'descricao' => 'Tomate, filé e queijo',
                'preco' => 39.00,
                'categoria_id' => $xpicanhaFile->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Filé Bacon',
                'descricao' => 'Tomate, filé, bacon e queijo',
                'preco' => 45.00,
                'categoria_id' => $xpicanhaFile->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Filé Misto',
                'descricao' => 'Tomate, filé e 5 fatias de queijo',
                'preco' => 45.00,
                'categoria_id' => $xpicanhaFile->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Filé e Frango',
                'descricao' => 'Tomate, filé, frango e queijo',
                'preco' => 39.00,
                'categoria_id' => $xpicanhaFile->id,
                'disponivel' => true,
                'imagem' => null,
            ],

            // --- X-FRANGO ---
            [
                'nome' => 'X-Frango',
                'descricao' => 'Tomate, frango e queijo',
                'preco' => 33.00,
                'categoria_id' => $xfrango->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Frango Bacon',
                'descricao' => 'Tomate, frango, bacon e queijo',
                'preco' => 39.00,
                'categoria_id' => $xfrango->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Frango Misto',
                'descricao' => 'Tomate, frango e 5 fatias de queijo',
                'preco' => 39.00,
                'categoria_id' => $xfrango->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Frango Palmito',
                'descricao' => 'Tomate, frango, palmito e queijo',
                'preco' => 39.00,
                'categoria_id' => $xfrango->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Americano (Frango)',
                'descricao' => 'Alface, tomate, milho, ervilha, hambúrguer, ovo, presunto e queijo',
                'preco' => 27.00,
                'categoria_id' => $xfrango->id,
                'disponivel' => true,
                'imagem' => null,
            ],

            // --- X-CALABRESA / BACON ---
            [
                'nome' => 'X-Calabresa',
                'descricao' => 'Tomate, hambúrguer, calabresa, presunto e queijo',
                'preco' => 30.00,
                'categoria_id' => $xcalabresaBacon->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Bacon',
                'descricao' => 'Tomate, hambúrguer, bacon, presunto e queijo',
                'preco' => 33.00,
                'categoria_id' => $xcalabresaBacon->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Xuxa',
                'descricao' => 'Tomate, milho, bacon, calabresa, presunto e queijo',
                'preco' => 33.00,
                'categoria_id' => $xcalabresaBacon->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Burgão',
                'descricao' => 'Tomate, 3 hambúrgueres e 3 fatias de queijo',
                'preco' => 35.00,
                'categoria_id' => $xcalabresaBacon->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Tudo',
                'descricao' => 'Tomate, milho, ervilha, hambúrguer, bacon, calabresa, ovo, salsicha, presunto e queijo',
                'preco' => 35.00,
                'categoria_id' => $xcalabresaBacon->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Labor',
                'descricao' => 'Tomate, ervilha, hambúrguer, calabresa, ovo, salsicha, presunto e queijo',
                'preco' => 33.00,
                'categoria_id' => $xcalabresaBacon->id,
                'disponivel' => true,
                'imagem' => null,
            ],

            // --- LANCHES NO PRATO ---
            [
                'nome' => 'X-Americano no prato',
                'descricao' => null,
                'preco' => 45.00,
                'categoria_id' => $lanchesPrato->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'X-Mais no prato',
                'descricao' => 'Alface, tomate, milho, ervilha, palmito, azeitona, bacon, calabresa, ovo, hambúrguer, frango, filé, presunto, queijo e torradas',
                'preco' => 55.00,
                'categoria_id' => $lanchesPrato->id,
                'disponivel' => true,
                'imagem' => null,
            ],

            // --- PORÇÕES ---
            [
                'nome' => 'Porção Salsicha Média',
                'descricao' => 'Salsicha, cebola, tomate e torradas',
                'preco' => 20.00,
                'categoria_id' => $porcoes->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Porção Salsicha Grande',
                'descricao' => 'Salsicha, cebola, tomate e torradas',
                'preco' => 30.00,
                'categoria_id' => $porcoes->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Porção Calabresa Média',
                'descricao' => 'Calabresa, cebola, tomate e torradas',
                'preco' => 40.00,
                'categoria_id' => $porcoes->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Porção Calabresa Grande',
                'descricao' => 'Calabresa, cebola, tomate e torradas',
                'preco' => 50.00,
                'categoria_id' => $porcoes->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Porção Frango Média',
                'descricao' => 'Frango, cebola, tomate e torradas',
                'preco' => 40.00,
                'categoria_id' => $porcoes->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Porção Frango Grande',
                'descricao' => 'Frango, cebola, tomate e torradas',
                'preco' => 50.00,
                'categoria_id' => $porcoes->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Porção Filé Média',
                'descricao' => 'Filé, cebola, tomate e torradas',
                'preco' => 55.00,
                'categoria_id' => $porcoes->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Porção Filé Grande',
                'descricao' => 'Filé, cebola, tomate e torradas',
                'preco' => 70.00,
                'categoria_id' => $porcoes->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Porção Filé e Frango Média',
                'descricao' => 'Filé, frango, cebola, tomate e torradas',
                'preco' => 50.00,
                'categoria_id' => $porcoes->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Porção Filé e Frango Grande',
                'descricao' => 'Filé, frango, cebola, tomate e torradas',
                'preco' => 65.00,
                'categoria_id' => $porcoes->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Porção Filé com Queijo Média',
                'descricao' => 'Filé, queijo, cebola, tomate e torradas',
                'preco' => 65.00,
                'categoria_id' => $porcoes->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Porção Filé com Queijo Grande',
                'descricao' => 'Filé, queijo, cebola, tomate e torradas',
                'preco' => 80.00,
                'categoria_id' => $porcoes->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Porção Picanha',
                'descricao' => 'Picanha, cebola, tomate e torradas',
                'preco' => 75.00,
                'categoria_id' => $porcoes->id,
                'disponivel' => true,
                'imagem' => null,
            ],

            // --- ACRÉSCIMOS ---
            [
                'nome' => 'Acréscimo Filé',
                'descricao' => null,
                'preco' => 10.00,
                'categoria_id' => $acrescimos->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Acréscimo Bacon',
                'descricao' => null,
                'preco' => 6.00,
                'categoria_id' => $acrescimos->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Acréscimo Frango',
                'descricao' => null,
                'preco' => 6.00,
                'categoria_id' => $acrescimos->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Acréscimo Calabresa',
                'descricao' => null,
                'preco' => 6.00,
                'categoria_id' => $acrescimos->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Acréscimo Hambúrguer',
                'descricao' => null,
                'preco' => 8.00,
                'categoria_id' => $acrescimos->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Acréscimo Palmito',
                'descricao' => null,
                'preco' => 6.00,
                'categoria_id' => $acrescimos->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Acréscimo Catupiry',
                'descricao' => null,
                'preco' => 3.00,
                'categoria_id' => $acrescimos->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Acréscimo Cheddar',
                'descricao' => null,
                'preco' => 3.00,
                'categoria_id' => $acrescimos->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Acréscimo Queijo',
                'descricao' => null,
                'preco' => 3.00,
                'categoria_id' => $acrescimos->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Acréscimo Batata',
                'descricao' => null,
                'preco' => 2.00,
                'categoria_id' => $acrescimos->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Acréscimo Ovo',
                'descricao' => null,
                'preco' => 2.00,
                'categoria_id' => $acrescimos->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Acréscimo Salsicha',
                'descricao' => null,
                'preco' => 2.00,
                'categoria_id' => $acrescimos->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Acréscimo Cebola',
                'descricao' => null,
                'preco' => 2.00,
                'categoria_id' => $acrescimos->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Acréscimo Milho',
                'descricao' => null,
                'preco' => 2.00,
                'categoria_id' => $acrescimos->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Acréscimo Ervilha',
                'descricao' => null,
                'preco' => 2.00,
                'categoria_id' => $acrescimos->id,
                'disponivel' => true,
                'imagem' => null,
            ],

            // --- BEBIDAS & SUCOS ---
            [
                'nome' => 'Coca-Cola 290ml',
                'descricao' => 'Lata',
                'preco' => 8.00,
                'categoria_id' => $bebidas->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Coca-Cola Lata',
                'descricao' => '350ml',
                'preco' => 10.00,
                'categoria_id' => $bebidas->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Coca-Cola 600ml',
                'descricao' => 'Garrafa',
                'preco' => 12.00,
                'categoria_id' => $bebidas->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Coca-Cola 1L',
                'descricao' => 'Garrafa',
                'preco' => 15.00,
                'categoria_id' => $bebidas->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Coca-Cola 2L',
                'descricao' => 'Garrafa',
                'preco' => 20.00,
                'categoria_id' => $bebidas->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Funada',
                'descricao' => null,
                'preco' => 10.00,
                'categoria_id' => $bebidas->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'H2O',
                'descricao' => null,
                'preco' => 15.00,
                'categoria_id' => $bebidas->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Fanta',
                'descricao' => null,
                'preco' => 6.00,
                'categoria_id' => $bebidas->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Sprite',
                'descricao' => null,
                'preco' => 13.00,
                'categoria_id' => $bebidas->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Schweppes',
                'descricao' => null,
                'preco' => 10.00,
                'categoria_id' => $bebidas->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Água (600ml)',
                'descricao' => null,
                'preco' => 6.00,
                'categoria_id' => $bebidas->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Água c/ gás (900ml)',
                'descricao' => null,
                'preco' => 9.00,
                'categoria_id' => $bebidas->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Cerveja Brahma (lata)',
                'descricao' => null,
                'preco' => 4.00,
                'categoria_id' => $bebidas->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Skol (lata)',
                'descricao' => null,
                'preco' => 3.00,
                'categoria_id' => $bebidas->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Suco de Laranja',
                'descricao' => null,
                'preco' => 13.00,
                'categoria_id' => $bebidas->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Suco de Maracujá',
                'descricao' => null,
                'preco' => 9.00,
                'categoria_id' => $bebidas->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Suco de Morango',
                'descricao' => null,
                'preco' => 6.00,
                'categoria_id' => $bebidas->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Suco de Limão',
                'descricao' => null,
                'preco' => 6.00,
                'categoria_id' => $bebidas->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Suco de Abacaxi',
                'descricao' => null,
                'preco' => 9.00,
                'categoria_id' => $bebidas->id,
                'disponivel' => true,
                'imagem' => null,
            ],
            [
                'nome' => 'Suco de Guaraná',
                'descricao' => null,
                'preco' => 9.00,
                'categoria_id' => $bebidas->id,
                'disponivel' => true,
                'imagem' => null,
            ],
        ];

        foreach ($produtos as $produto) {
            Produto::create($produto);
        }
    }
}