services:
  mysql:
    image: mysql:8.0
    container_name: cardapio-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cardapio_db
      MYSQL_USER: lanchonete
      MYSQL_PASSWORD: lanchonete123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cardapio-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: cardapio-backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: mysql
      DB_DATABASE: cardapio_db
      DB_USERNAME: lanchonete
      DB_PASSWORD: lanchonete123
    networks:
      - cardapio-network
    depends_on:
      - mysql

  nginx:
    image: nginx:1.25.3-alpine
    container_name: cardapio-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cardapio-network
    depends_on:
      - backend

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cardapio-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      REACT_APP_API_URL: http://localhost:8000
    networks:
      - cardapio-network
    depends_on:
      - nginx

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cardapio-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - cardapio-network
    depends_on:
      - mysql

volumes:
  mysql_data:

networks:
  cardapio-network:
    driver: bridge